import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, AreaChart, Area } from "recharts";

const scoreTrend = [
  { month: "Sep", avg: 580 }, { month: "Oct", avg: 588 }, { month: "Nov", avg: 595 },
  { month: "Dec", avg: 601 }, { month: "Jan", avg: 607 }, { month: "Feb", avg: 612 },
];

const bureauComparison = [
  { name: "TransUnion", reports: 1245, accuracy: 94 },
  { name: "Metropol", reports: 987, accuracy: 91 },
  { name: "Athena", reports: 1355, accuracy: 96 },
];

const sectorExposure = [
  { sector: "Banking", value: 45 }, { sector: "Sacco", value: 22 }, { sector: "MFI", value: 15 },
  { sector: "Mobile", value: 12 }, { sector: "Other", value: 6 },
];

const tooltipStyle = { background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: "8px", fontSize: "12px" };

export default function AdminAnalytics() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Analytics</h1>
        <p className="text-sm text-muted-foreground">Bureau-wide performance analytics and trends.</p>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        <Card className="border-border/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Average Credit Score Trend</CardTitle>
            <CardDescription>Portfolio average score over 6 months</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={250}>
              <AreaChart data={scoreTrend}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                <XAxis dataKey="month" className="text-xs" />
                <YAxis domain={[550, 650]} className="text-xs" />
                <Tooltip contentStyle={tooltipStyle} />
                <Area type="monotone" dataKey="avg" stroke="hsl(var(--primary))" fill="hsl(var(--primary) / 0.1)" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="border-border/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Bureau Comparison</CardTitle>
            <CardDescription>Reports generated by bureau source</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={250}>
              <BarChart data={bureauComparison}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                <XAxis dataKey="name" className="text-xs" />
                <YAxis className="text-xs" />
                <Tooltip contentStyle={tooltipStyle} />
                <Bar dataKey="reports" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="lg:col-span-2 border-border/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Sector Exposure</CardTitle>
            <CardDescription>Credit distribution by sector</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {sectorExposure.map((s) => (
                <div key={s.sector} className="flex items-center gap-4">
                  <span className="text-sm w-20">{s.sector}</span>
                  <div className="flex-1 h-6 bg-muted rounded-full overflow-hidden">
                    <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${s.value}%` }} />
                  </div>
                  <span className="text-sm font-medium w-10 text-right">{s.value}%</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
